development:
  adapter: postgresql
  database: alert_dev
  username: postgres
  password: 
  host: localhost

test:
  adapter: postgresql
  database: alert_test
  username: postgres
  password: 
  host: localhost

production:
  adapter: postgresql
  database: alert_prod
  username: postgres
  password: 
  host: localhost